### ISSUE TITLE
opening symlink to nvim/init.vim

### ISSUE THREAD

**Issue by fasterbru** [mhinz/vim-startify#373] opened 2019-05-22 20:21 UTC
I use bookmarks to my configs which place in ~/configuration.

So, when i open ~/configuration/nvim/init.vim via bookmarks:
```
let g:startify_bookmarks = [  
      \ {'c': '~/configuration/nvim/init.vim'},  
      \ {'z': '~/configuration/terminal/zshrc'}  
      \ ]
```
I get opened file with path ~/.config/nvim/init.vim (which is symlink to ~/configuration/nvim/init.vim). And thus fugitive doesn't work. But when i open zshrc via bookmarks, all works fine. Even it is symlink too.

I don't know who to think

**Comment by fasterbru** [comment] 2019-05-23 06:44
Im trying to reproduce this behavior on other machine with the same configuration. And all works fine

**Comment by mhinz** [comment] 2019-05-25 17:02
Since it appears to be an environmental issue and that there's nothing I can do reproduce it, I'm closing this. :)

I guess the best you can do is to find out all the differences between both machines (not a very helpful tip, I know). Same Vim/Nvim version? Same plugin versions? Same symlinks? Maybe even same git version? etc.

**Closed by mhinz** 2019-05-25 17:02 UTC
