### ISSUE TITLE
Feature request: Startup time

### ISSUE THREAD

**Issue by jamischarles** [mhinz/vim-startify#291] opened 2017-09-13 05:53 UTC
Love this. I've recently become obsesses with tracking shell startup time, and it's a great way to see when you've installed something or several somethings that slow down startup speed.

Any way this could include vim startup time?

I imagine it'd work something like:
`nvim --startuptime someFileName`

And then we read the last line of the file, and display that on the page
`517.225  000.004: --- NVIM STARTED ---`

If you're busy, and interested in this, I can issue a PR. Thoughts?

**Comment by mhinz** [comment] 2017-09-13 14:58
Well, I'm not sure how this is supposed to work together with Startify, because I neither know whether `--startuptime` was given or not nor do I know the argument that was given to it.

In my opinion, startup time isn't something you want to see at every Vim start. You want to check it only if the start feels too slow and you need numbers.

For the latter I suggest using [vim-startuptime](https://github.com/tweekmonster/startuptime.vim) which exposes the `:StartupTime` command.

**Comment by mhinz** [comment] 2017-09-14 09:45
For the reasons mentioned above, I'm closing this.

Nevertheless, thanks for bringing it up! ✨

**Closed by mhinz** 2017-09-14 09:45 UTC
Labels: feature request

**Comment by fftyjw** [comment] 2017-12-25 10:24
I am using startify on windows 10 with GVIM, and the startup time is very long. I use --startuptime flag which provide by gvim to record what happend on startup, and this is what I get:

1098.000  016.000: BufEnter autocommands
1098.000  000.000: editing files in windows
1104.000  002.000  002.000: sourcing D:\00-code\mysettings\vimfiles\bundle\vim-startify\autoload\startify.vim
1106.000  000.000  000.000: sourcing D:\00-code\mysettings\vimfiles\bundle\vim-startify\autoload\startify\fortune.vim
32162.000  000.000  000.000: sourcing D:\00-code\mysettings\vimfiles\bundle\vim-startify\syntax\startify.vim

According to the record, the fortune.vim used almost 30 seconds on vim startup.

**Comment by mhinz** [comment] 2017-12-25 23:01
When you use `:Startify` from within gvim is it still slow? If so, please use https://github.com/mhinz/vim-galore#profiling-at-runtime to find out more about which functions are taking so long.

Which Startify options do you set in your vimrc?

**Comment by fftyjw** [comment] 2017-12-26 01:37
When use :Startify from within gvim, it is very fast.

**Comment by mhinz** [comment] 2017-12-26 14:53
Sometimes the underlying syscalls of the operating system can take a long time due to various reasons. E.g. when accessing remote file systems.

There's nothing with that line of code per se and I can't reproduce it in my Windows 10 VM, so, whatever the reason, the best advice I can give is to enable Startify's unsafe mode:

```vim
" :h g:startify_enable_unsafe
let g:startify_enable_unsafe = 1
```

This mode avoids most expensive syscalls and should fix the long startup (at the cost of potential duplicate entries).
