### ISSUE TITLE
GVim Cannot Show Unicode Fortune nor Tab Characters

### ISSUE THREAD

**Issue by Neur1n** [mhinz/vim-startify#344] opened 2018-12-02 09:50 UTC
Hello. I have not touched GVim for a while on Windows, and a few days ago when I upgraded GVim to the [latest nightly build](https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0553) (on that day), I found that the it cannot show unicode fortune anymore and "fall back" to ASCII instead, neither my customized tab chatacters. But the same configuration in Neovim works fine. I have tried to change the font, the build of GVim, and load Startify only, but nothing happened. Any help is much appreciated.

![gvim](https://user-images.githubusercontent.com/17579247/49338270-28650a00-f65a-11e8-9b6b-0d38baafa385.png)
![neovim](https://user-images.githubusercontent.com/17579247/49338277-2ef38180-f65a-11e8-8313-25e4ab54927a.png)

**Comment by mhinz** [comment] 2018-12-02 16:17
Well, comparing Neovim in a terminal and Vim with a GUI are totally different things. :>

They also have different default values, so it might be because of options that are _not_ in your vimrc.

Maybe `:set enc=utf-8` is enough?

When you paste your exact `g:startify_custom_header`, then I can try to reproduce it on my Win 10 VM.

**Comment by mhinz** [comment] 2018-12-02 18:16
That [8.1.533](https://github.com/vim/vim-win32-installer/releases/download/v8.1.0553/gvim_8.1.0553_x64-mui2.exe) and your config works as expected for me on Win 10.

Does `:set enc=utf-8 guifont=Consolas:h10:b` make a difference?

**Comment by mhinz** [comment] 2018-12-03 23:04
I'm closing this, since it's not related to the plugin itself. The concerning code didn't change in months.

This is most probably either a problem with the font or the distributed build of gVim. Maybe installing an older version makes it work again? Tried a minimal vimrc? Should I take a look at it?

Please report back any findings. Now where my Win VM is set up, I'll gladly help with testing things.

**Closed by mhinz** 2018-12-03 23:04 UTC
