### ISSUE TITLE
Slow startup with UltiSnips

### ISSUE THREAD

**Issue by mcchrish** [mhinz/vim-startify#201] opened 2016-02-19 13:45 UTC
Minimal vimrc:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'mhinz/vim-startify'
Plug 'SirVer/ultisnips'
call plug#end()
```

There is about 150 milliseconds spike when loading Ultisnips when Startify is present.
**Neovim**
**Ultisnips + Startify**
```


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.011  000.011: --- NVIM STARTING ---
000.523  000.512: locale set
001.011  000.488: inits 1
001.023  000.012: window checked
001.330  000.307: parsing arguments
001.333  000.003: expanding arguments
001.379  000.046: inits 2
001.500  000.121: init highlight
002.979  001.333  001.333: sourcing /Users/mclopez/.config/nvim/autoload/plug.vim
003.467  000.024  000.024: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftoff.vim
016.795  000.054  000.054: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/ftdetect/UltiSnips.vim
016.862  000.028  000.028: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/ftdetect/snippets.vim
017.026  013.223  013.141: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/filetype.vim
017.172  000.039  000.039: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftplugin.vim
017.298  000.031  000.031: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/indent.vim
017.742  000.188  000.188: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syncolor.vim
017.841  000.373  000.186: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/synload.vim
017.870  000.485  000.111: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syntax.vim
017.883  016.294  001.159: sourcing vimrc.min
017.888  000.095: sourcing vimrc file(s)
018.133  000.113  000.113: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/plugin/startify.vim
018.474  000.059  000.059: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/pythonx.vim
064.168  000.207  000.207: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/remote/host.vim
064.272  045.936  045.670: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/python3.vim
064.489  000.074  000.074: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim
064.556  046.325  000.314: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/plugin/UltiSnips.vim
065.043  000.141  000.141: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/gzip.vim
065.090  000.018  000.018: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/man.vim
065.561  000.445  000.445: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchit.vim
065.729  000.137  000.137: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchparen.vim
066.148  000.390  000.390: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/netrwPlugin.vim
066.225  000.034  000.034: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rplugin.vim
066.268  000.011  000.011: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rrhelper.vim
066.374  000.075  000.075: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/shada.vim
066.438  000.021  000.021: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/spellfile.vim
066.581  000.112  000.112: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tarPlugin.vim
066.691  000.076  000.076: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tohtml.vim
066.745  000.019  000.019: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tutor.vim
066.871  000.094  000.094: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/vimballPlugin.vim
067.052  000.139  000.139: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/zipPlugin.vim
067.275  000.074  000.074: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/after/plugin/UltiSnips_after.vim
067.292  001.178: loading plugins
067.299  000.007: inits 3
079.845  012.546: reading ShaDa
080.341  000.495: clearing screen
081.491  001.150: opening buffers
081.560  000.069: BufEnter autocommands
081.564  000.004: editing files in windows
082.285  000.574  000.574: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/autoload/startify.vim
219.928  130.752  130.752: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/autoload/UltiSnips.vim
222.334  000.182  000.182: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/syntax/startify.vim
222.694  009.622: VimEnter autocommands
222.697  000.003: before starting main loop
234.598  011.901: first screen update
234.603  000.005: --- NVIM STARTED ---
```
**Ultisnips Only**
```


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.011  000.011: --- NVIM STARTING ---
000.508  000.497: locale set
001.041  000.533: inits 1
001.053  000.012: window checked
001.346  000.292: parsing arguments
001.348  000.002: expanding arguments
001.392  000.044: inits 2
001.511  000.118: init highlight
002.972  001.319  001.319: sourcing /Users/mclopez/.config/nvim/autoload/plug.vim
003.346  000.024  000.024: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftoff.vim
018.370  000.045  000.045: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/ftdetect/UltiSnips.vim
018.430  000.027  000.027: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/ftdetect/snippets.vim
018.582  014.942  014.870: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/filetype.vim
018.702  000.033  000.033: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftplugin.vim
018.812  000.029  000.029: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/indent.vim
019.231  000.184  000.184: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syncolor.vim
019.332  000.363  000.179: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/synload.vim
019.361  000.469  000.106: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syntax.vim
019.373  017.776  000.960: sourcing vimrc.min
019.378  000.091: sourcing vimrc file(s)
019.762  000.055  000.055: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/pythonx.vim
068.784  000.213  000.213: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/remote/host.vim
068.896  049.263  048.994: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/python3.vim
069.105  000.075  000.075: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim
069.182  049.644  000.306: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/plugin/UltiSnips.vim
069.705  000.162  000.162: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/gzip.vim
069.750  000.016  000.016: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/man.vim
070.232  000.456  000.456: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchit.vim
070.399  000.135  000.135: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchparen.vim
070.805  000.378  000.378: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/netrwPlugin.vim
070.884  000.036  000.036: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rplugin.vim
070.927  000.011  000.011: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rrhelper.vim
071.032  000.074  000.074: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/shada.vim
071.097  000.024  000.024: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/spellfile.vim
071.235  000.106  000.106: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tarPlugin.vim
071.347  000.076  000.076: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tohtml.vim
071.397  000.018  000.018: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tutor.vim
071.529  000.099  000.099: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/vimballPlugin.vim
071.708  000.137  000.137: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/zipPlugin.vim
071.930  000.075  000.075: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/after/plugin/UltiSnips_after.vim
071.948  001.123: loading plugins
071.955  000.007: inits 3
084.807  012.853: reading ShaDa
085.394  000.586: clearing screen
086.646  001.252: opening buffers
086.694  000.048: BufEnter autocommands
086.698  000.004: editing files in windows
086.802  000.104: VimEnter autocommands
086.804  000.002: before starting main loop
103.519  016.714: first screen update
103.524  000.005: --- NVIM STARTED ---
```
**Startify Only**
```


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.010  000.010: --- NVIM STARTING ---
000.480  000.470: locale set
001.018  000.538: inits 1
001.030  000.012: window checked
001.331  000.301: parsing arguments
001.334  000.003: expanding arguments
001.380  000.046: inits 2
001.501  000.121: init highlight
002.983  001.338  001.338: sourcing /Users/mclopez/.config/nvim/autoload/plug.vim
003.365  000.025  000.025: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftoff.vim
016.880  013.227  013.227: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/filetype.vim
017.072  000.044  000.044: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftplugin.vim
017.183  000.029  000.029: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/indent.vim
017.615  000.187  000.187: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syncolor.vim
017.715  000.369  000.181: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/synload.vim
017.743  000.474  000.106: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syntax.vim
017.755  016.166  001.030: sourcing vimrc.min
017.761  000.093: sourcing vimrc file(s)
018.022  000.105  000.105: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/plugin/startify.vim
018.521  000.156  000.156: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/gzip.vim
018.568  000.017  000.017: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/man.vim
019.070  000.474  000.474: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchit.vim
019.369  000.148  000.148: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchparen.vim
019.792  000.390  000.390: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/netrwPlugin.vim
020.110  000.184  000.184: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/remote/host.vim
020.138  000.300  000.116: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rplugin.vim
020.183  000.011  000.011: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rrhelper.vim
020.292  000.077  000.077: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/shada.vim
020.357  000.022  000.022: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/spellfile.vim
020.503  000.115  000.115: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tarPlugin.vim
020.617  000.078  000.078: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tohtml.vim
020.666  000.017  000.017: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tutor.vim
020.796  000.098  000.098: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/vimballPlugin.vim
020.988  000.149  000.149: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/zipPlugin.vim
021.046  001.130: loading plugins
021.050  000.004: inits 3
038.204  017.154: reading ShaDa
038.757  000.553: clearing screen
039.966  001.210: opening buffers
040.024  000.057: BufEnter autocommands
040.027  000.003: editing files in windows
040.756  000.598  000.598: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/autoload/startify.vim
048.657  000.163  000.163: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/syntax/startify.vim
048.949  008.160: VimEnter autocommands
048.952  000.003: before starting main loop
061.319  012.367: first screen update
061.326  000.007: --- NVIM STARTED ---
```

**Vim**
```


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.005  000.005: --- VIM STARTING ---
000.070  000.065: Allocated generic buffers
000.163  000.093: locale set
000.174  000.011: GUI prepared
000.177  000.003: clipboard setup
000.183  000.006: window checked
000.622  000.439: inits 1
000.631  000.009: parsing arguments
004.772  004.141: expanding arguments
009.174  004.402: shell init
009.580  000.406: Termcap init
009.617  000.037: inits 2
011.782  002.165: init highlight
013.396  001.494  001.494: sourcing /Users/mclopez/.vim/autoload/plug.vim
013.864  000.021  000.021: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/ftoff.vim
037.432  000.060  000.060: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/ftdetect/snippets.vim
037.521  000.060  000.060: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/ftdetect/UltiSnips.vim
037.674  023.483  023.363: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
037.791  000.041  000.041: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
037.896  000.033  000.033: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/indent.vim
038.403  000.284  000.284: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
038.522  000.480  000.196: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
038.556  000.593  000.113: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
038.572  026.733  001.068: sourcing vimrc.min
038.576  000.061: sourcing vimrc file(s)
038.743  000.015  000.015: sourcing /Users/mclopez/.config/nvim/plugged/vim-startify/plugin/startify.vim
038.844  000.014  000.014: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/plugin/UltiSnips.vim
039.258  000.026  000.026: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
039.300  000.018  000.018: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
039.350  000.027  000.027: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
039.395  000.022  000.022: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
039.441  000.021  000.021: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
039.509  000.046  000.046: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
039.553  000.022  000.022: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
039.600  000.025  000.025: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
039.708  000.086  000.086: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
039.754  000.023  000.023: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
039.800  000.025  000.025: sourcing /usr/local/Cellar/macvim/7.4-96/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
039.922  000.017  000.017: sourcing /Users/mclopez/.config/nvim/plugged/ultisnips/after/plugin/UltiSnips_after.vim
039.937  000.974: loading plugins
039.942  000.005: inits 3
039.960  000.018: setting raw mode
039.975  000.015: start termcap
040.006  000.031: clearing screen
040.101  000.095: opening buffers
040.106  000.005: BufEnter autocommands
040.109  000.003: editing files in windows
040.122  000.013: VimEnter autocommands
040.125  000.003: before starting main loop
041.438  001.313: first screen update
041.440  000.002: --- VIM STARTED ---
```

Seems to be in Neovim only.
Version `NVIM v0.1.3-37-gdcdb50b`

**Comment by mhinz** [comment] 2016-02-20 11:24
Hmm, very weird, but I can reproduce it with Neovim. I'll look into it.

**Comment by mhinz** [comment] 2016-03-01 13:56
Okay, it's a bug in Neovim/[python-client](https://github.com/neovim/python-client) bug.

The problem is that UltiSnips calls `:python` in `ftdetect` already which leads to loading the Python host which currently happens in a _synchronous_ fashion (polling). Most of the time stems from importing these modules:

```
time python -c 'import trollius'
time python3 -c 'import asyncio'
```

Hopefully this will be fixed soon!

**Comment by mhinz** [comment] 2016-03-21 22:01
Since this is no Startify issue, I close this.

p.s. they improved Python host startup time quite a bit lately.

**Closed by mhinz** 2016-03-21 22:01 UTC
Labels: neovim
