### ISSUE TITLE
Problem: Folds are saved only for one window but not for all open windows 

### ISSUE THREAD

**Issue by Annis-Monadjem** [mhinz/vim-startify#233] opened 2016-07-10 10:41 UTC
Hello Marco! 
Vim-Startify is really great! I love it and thanks for such a wonderful product in Vim toolbox.
I'm having a problem however with saving folds for all open windows. 
Vim-startify properly saves folds for only one open window. When i have many open windows, and in particular, when I am returning to multiple saved windows of same buffer and reopen using vim-startify all except one window will lose manual folds.
Is there anything I'm doing wrong? 
And how is it possible to retain folds on all windows of same buffer?

Below is my setup in vimrc (the piece for vim-startify):
set sessionoptions+=curdir,folds,help,options,resize,tabpages,winpos,winsize
set sessionoptions-=blank
set sessionoptions-=buffers

" How to disable random quotes header?~
let g:startify_custom_header = []

" The directory to save/load sessions to/from.
let g:startify_session_dir = '~/.vim/.sessions_2'

let g:startify_list_order = [
        \ ['   These are my sessions:'],
        \ 'sessions',
        \ ['   My Most Recently Used Files:'],
        \ 'files',
        \ ['   My Most Recently Used Files In The Current Directory:'],
        \ 'dir',
        \ ]

" Usually |v:oldfiles| only gets updated when Vim exits. Using this option updates
" it on-the-fly, so that :Startify is always up-to-date.
let g:startify_update_oldfiles = 1

" Don't run Startify at Vim startup. You can still call it anytime via :Startify.
let g:startify_disable_at_vimenter = 1 

" Show filenames relative to the current working directory instead of as
" absolute paths. This only applies to the "files" list, since the "dir" list is
" relative by nature.
let g:startify_relative_path = 0

" If you fire up "vim" in a directory that contains a "Session.vim", that session
" will be loaded automatically. Otherwise it will be shown as the top entry in
" the Startify buffer.
" This also works if you open a bookmarked directory.
" Great way to create a portable project folder.
let g:startify_session_autoload = 1

" Delete open buffers before loading a new session.
let g:startify_session_delete_buffers = 1

" When opening a file or bookmark, change to its directory.
let g:startify_change_to_dir = 1

Please, let me know please what i can do to optimize my working in vim-startify and remove the above bug. 
Thanks.

**Comment by mhinz** [comment] 2016-07-10 15:46
> Vim-Startify is really great! I love it and thanks for such a wonderful product in Vim toolbox.

Thanks!

> And how is it possible to retain folds on all windows of same buffer?

The only thing that Startify really does is doing `sessionoptions-=options` before saving (if set) and restoring it afterwards. This is done due to many session problems because of saved options. (Most session managers do that.)

But I can reproduce what you see and it seems to be a Vim bug. The same happens if you just use `:mksession` and `vim -S Session.vim` directly. The funny thing is.. a session file is really just a collection of commands to restore reproduce a certain environment and looking at my test `Session.vim`, I can actually see how it uses something like `3,6fold` to re-create the manual folds in _both_ windows. But effectively it only works in the window you land into.

I close this, since it's not a Startify issue, but continue looking into it and report my findings in here. In the worst case I'll send a report to [@vim_dev](https://groups.google.com/forum/#!forum/vim_dev).

**Closed by mhinz** 2016-07-10 15:46 UTC

**Comment by mhinz** [comment] 2016-07-11 10:17
Okay, I found the root of the problem. The session file basically does this in my test:

```vim
:edit foo
:set fdm=manual
:1,2fold
:vsplit
:edit foo
set fdm=manual
1,2fold
```

Now `:h fold-manual` says: *The manual folds are lost when you abandon the file.* And that's exactly what happens if you use `:edit`.

You can simply try it yourself: `zfj` to create a new fold. `:e` for "reloading" (this is abandoning and reloading) the current file will remove the fold.

I'd say this isn't even a bug, just the way Vim works and coming up with a workaround for it in the code that generates the session file would be extremely complicated.

**Comment by Annis-Monadjem** [comment] 2016-07-11 10:49
Well this is exactly what I don't do and so your comments although interesting are not a solution to the problem I described earlier. 
I have not `edit` the buffer and my steps are as follow:
```
:edit foo
:set fdm=manual
:1,2fold
:vsplit
:SSave
```

On loading `:SLoad` the destination window does not have folds. 
So the problem is unfortunately persisting. How can this problem be solved?

Also, I'm not insisting to use `set fdm=manual` except that I need to have control over which rows/lines are to be folded. 

It would be nice if this problem could be resolved. This is a serious weakness in `session` functionality! Or otherwise what other alternative solutions are there in vim ?

Thanks

**Comment by Annis-Monadjem** [comment] 2016-07-11 11:24
Well this is exactly what I don't do and so your comments although interesting are not a solution to the problem I described earlier. 
I have not edit the buffer and my steps are as follow::edit foo
:set fdm=manual
:1,2fold
:vsplit
:SSave
On loading :SLoad the destination window does not have folds. 
So the problem is unfortunately persisting. How can this problem be solved?Also, I'm not insisting to use set fdm=manual except that I need to have control over which rows/lines are to be folded.It would be nice if this problem could be resolved. This is a serious weakness in session functionality! Or otherwise what other alternative solutions are there in vim ?Thanks
 

    On Monday, July 11, 2016 12:17 PM, Marco Hinz <notifications@github.com> wrote:
 
 

 Okay, I found the root of the problem. The session file basically does this in my test::edit foo
:set fdm=manual
:1,2fold
:vsplit
:edit foo
set fdm=manual
1,2foldNow :h fold-manual says: The manual folds are lost when you abandon the file. And that's exactly what happens if you use :edit.You can simply try it yourself: zfj to create a new fold. :e for "reloading" (this is abandoning and reloading) the current file will remove the fold.I'd say this isn't even a bug, just the way Vim works and coming up with a workaround for it in the code that generates the session file would be extremely complicated. —

**Comment by mhinz** [comment] 2016-07-11 12:15
Sessions are a Vim feature. Startify provides simple commands that wrap around `:mksession` and `:source`, so that all session files are always put in the same directory. Otherwise the Startify buffer couldn't list them. 

The steps I mentioned above are automatically put into the session files by Vim itself.

`:edit` is executed for every window when a session is reproduced from a session file. So when the session file consists out of 2 windows both showing the same buffer with a manual fold, the session file will look like this:

```vim
edit foo
1,2fold
vsplit
edit foo
1,2fold
```

And here the second `:edit` will remove the manual of the first window.

Sadly there's no way I (or anyone else) can do anything about it without Vim changing the way `:mksession` works.

> Also, I'm not insisting to use set `fdm=manual` except that I need to have control over which rows/lines are to be folded.

Then I'd suggest to use `fdm=marker`. In that case also have a look at `:h 'foldmarker'`. By default `{{{` marks the beginning line of a fold and `}}}` the closing line.

**Comment by Annis-Monadjem** [comment] 2016-07-11 21:33
Thank You.

**Comment by Annis-Monadjem** [comment] 2016-07-12 14:37
I'm writing this because I think your `vim-startify` is an excellent 
plugin and i think other users should know about it. I was nearly going 
to drop it however because of the problem i described to your earlier. 
Your answers unfortunately did not help me much. Hence, I'm sharing with 
you what I found and what makes it really to work for me.

What I found is that i can fix the problem (described ealier) 
suprisingly easily with just `se fdm=indent`. This solution works 
excellently well with `html` and embedded `css`, `js`.

_The final result_:
Files with `.html` extension with `.html` syntax are properly indented 
and `vim-startify` properly saves folding for all open windows !

I'm writing this so you can share this piece of info to other 
`vim-startify` users !

You can now close the case with the solution above.

Good luck






-------- Forwarded Message --------
Subject: 	Re: [mhinz/vim-startify] Problem: Folds are saved only for one 
window but not for all open windows (#233)
Date: 	Mon, 11 Jul 2016 05:15:30 -0700

**Comment by mhinz** [comment] 2016-07-12 14:55
I know all kinds of folds, but thought `marker` would be more fitting for you, since you wanted full control. With `syntax` the folding is based on the rules of the particular filetype.

Anyway, I'm glad it's working for you now!

**Comment by mhinz** [comment] 2016-07-12 14:57
Another thing I forgot to mention: syntax rules in Vim are based on regular expressions and some filetypes are more complicated to parse than others. E.g. big Ruby files are known to become quite slow with `foldmethod=syntax`, unless you also have the FastFold plugin installed:

See https://github.com/mhinz/vim-galore#folding
