### ISSUE TITLE
Startify echoes all files before Vim actually opens

### ISSUE THREAD

**Issue by krzkrzkrz** [mhinz/vim-startify#173] opened 2015-07-12 08:17 UTC
Im trying to echo the file path when entering a buffer. Not before Vim starts. I have:

    autocmd BufEnter * :echo @%

When I start a Startify Vim session. It actually echoes all the files first, before Vim actually opens

**Comment by mhinz** [comment] 2015-07-12 13:54
Hi there,

what do you mean with `Startify Vim session`? Do you mean just starting Vim without arguments, so `:Startify` is triggered or do you talk about actual _Vim sessions_ as in `:h views-sessions`?

I put that autocmd in my vimrc. When I start Vim and `:Startify` gets triggered, nothings gets shown, since the buffer has no name. When I now open several entries at once (by marking them with `b`), each file gets opened and therefore the autocmd outputs all their names.

> It actually echoes all the files first, before Vim actually opens

Could you tell me the exact steps to reproduce this?

**Comment by krzkrzkrz** [comment] 2015-07-12 14:37
Hi,

Open a few buffers in Vim. Then `:SSave`. Give it a session name (i.e. `foobar`). Quite Vim (`:qa`).

In the terminal. Execute `vim -S ~/.vim/session/foobar` (assuming your sessions are stored in `~/.vim/session/`)

**Comment by mhinz** [comment] 2015-07-12 16:56
I close this since it's no Startify problem.

(But feel free to ask further questions in `#vim`. :-))

**Closed by mhinz** 2015-07-12 16:56 UTC
