### ISSUE TITLE
startify showing after session load by CtrlSpace

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-startify#279] opened 2017-03-31 17:12 UTC
I am stuck with the https://github.com/vim-ctrlspace/vim-ctrlspace plugin for session loading as I like the idea of separate buffer lists for tab pages.

With https://github.com/vim-ctrlspace/vim-ctrlspace and https://github.com/vim-pandoc/vim-pandoc and vim-startify, if not
```vim
let g:startify_session_delete_buffers = 0
let g:startify_session_number = 0
```
then after a session load by CtrlSpace on VimEnter (in a directory where a session file is present) then `:Startify` is called after loading the session. This is not intended and was not there before.

This behavior was introduced by commits

72c51e773a7f0fcb2963b17816fdde856e7774d1

and 

579b10672412449a6abe682847b828775909258a

**Comment by mhinz** [comment] 2017-03-31 17:52
Hmm.

So both plugins run at VimEnter and CtrlSpace happens to run first. (They execute in the order the autocmds were given, so your plugin manager probably sources CtrlSpace before Startify.)

The session gets loaded and in the end you land in the Startify buffer, right? This can only happen if Vim thinks the current buffer contains _no single byte_, which should only be the case for _new_ buffers. ([Code](https://github.com/mhinz/vim-startify/blob/2e89a6ec2b34d55bf3b85a3df863da5156bce2d5/plugin/startify.vim#L36)).

I can't really see how the two mentioned options and commits should interfere here:

- `g:startify_session_delete_buffers` doesn't matter since sessions are handled by CtrlSpace
- `g:startify_session_session_number` merely changes the number of sessions shown in the Startify buffer

Maybe it just worked before because the sourcing order used to be different? I can imagine Startify getting sourced first, then you land in the Startify buffer, then CtrlSpace sources the session (which makes the Startify buffer delete itself).

Or do you use any other Startify options that weren't mentioned?

---

Alternatively, you could disable that session loading by CtrlSpace (I'm sure there's an option for it) and use Startify for that: [`let g:startify_session_autoload = 1`](https://github.com/mhinz/vim-startify/blob/2e89a6ec2b34d55bf3b85a3df863da5156bce2d5/plugin/startify.vim#L37)

**Comment by Konfekt** [comment] 2017-03-31 21:24
Yeah, the interplay is complicated. In fact, the pandoc plugin is the crux. CtrlSpace itself does not cause problems. 

Strangely each of those two commits broke the behavior each time. 

The two options mitigate the problem, but only erratically. There are no other options interfering. 

I'd prefer to keep CtrlSpace as a session loader in the meanwhile, but I see that this is a tangled bug report. Most mysterious why those two commits broke the behavior, even with the corresponding options set to revert them in a way.

**Comment by mhinz** [comment] 2017-03-31 23:58
Hmm, the changes themselves should be fine from the plugin's point of view. The development of ctrlspace seems to have stalled, though.. ;-)

Anyway, if you can come up with a minimal config that reproduces this problem, I might add a workaround.

```vim
" /tmp/vimrc

call plug#begin('/tmp')
  Plug 'mhinz/vim-startify'
  Plug 'vim-ctrlspace/vim-ctrlspace'
  Plug 'vim-pandoc/vim-pandoc'
call plug#end()

filetype plugin indent on

" needed by ctrlspace
set hidden
```

Then `vim -Nu vimrc` in `/tmp` doesn't do anything, although there's a `/tmp/Session.vim`. Do I have to do something to get ctrlspace to autoload the session on VimEnter?

**Comment by mhinz** [comment] 2017-05-14 00:02
(Since this issue seems to be pretty particular and I don't know how to reproduce it, I'm closing this. Feel free to reopen.)

**Closed by mhinz** 2017-05-14 00:02 UTC
Labels: waiting:repro
